Repository dripcoder20/flexmart-auth, pull requests merged in 2020-06, with the labels that each got.

#51 42 - Update Page UI
  .gitignore
  .php_cs
  app/Events/UserHasLoggedIn.php
  app/Exceptions/Handler.php
  app/Http/Controllers/Api/AuthController.php
  app/Http/Controllers/Api/MobileValidationController.php
  app/Http/Controllers/Api/RegistrationController.php
  app/Http/Controllers/Api/VerificationController.php
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/MobileVerificationController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/ValidateMobileController.php
  app/Listeners/RecordLoginHistory.php
  app/Providers/AuthServiceProvider.php
  app/User.php
  libraries/Otp.php
  package-lock.json
  package.json
  public/mix-manifest.json
  resources/js/app.js
  resources/js/components/LoginForm.vue
  resources/js/components/Logo.vue
  resources/js/components/MobileValidationForm.vue
  resources/js/components/RegisterForm.vue
  resources/js/components/VerificationForm.vue
  resources/views/verify.blade.php
  routes/api.php
  routes/web.php
  tests/Feature/MobileValidationTest.php
  tests/Feature/User/UserLoginTest.php
  tests/Feature/User/UserLogoutTest.php
  tests/Feature/User/UserProfileTest.php
  tests/Feature/User/UserRegistrationTest.php
  tests/Feature/VerificationTest.php
  tests/Unit/App/ExceptionHandlerTest.php
  tests/Unit/OtpTest.php
  tests/Unit/middleware/AuthenticateTest.php
Labels: [zube]: In Review

#52 Added resend countdown and mobile prefix validation
  app/Http/Controllers/Api/MobileValidationController.php
  public/mix-manifest.json
  resources/js/components/MobileNumber.vue
  resources/js/components/VerificationForm.vue
  tests/Feature/MobileValidationTest.php
Labels: [zube]: In Review, code review, enhancement

#56 55 refactor routes for mobile verification
  app/Http/Controllers/Api/MobileValidationController.php
  app/Http/Controllers/Api/MobileVerificationController.php
  app/Http/Controllers/ValidateMobileController.php
  public/mix-manifest.json
  resources/js/components/MobileValidationForm.vue
  resources/js/components/VerificationForm.vue
  resources/lang/en/validation.php
  resources/views/validate-mobile.blade.php
  routes/api.php
  routes/web.php
  tests/Feature/MobileValidationTest.php
  tests/Feature/User/UserRegistrationTest.php
  tests/Feature/VerificationTest.php
Labels: [zube]: Inbox
